### ISSUE TITLE
Evolutionary Algorithm slowdown

### ISSUE THREAD

**Issue by pklehre** [ocaml-multicore/ocaml-multicore#336] opened 2020-05-06 15:56 UTC
Here is a minimal implementation of an evolutionary algorithm. It slows down when the number of cores increases. I suspect this is a similar issue to #333

```ocaml

let doc =
"
A minimal multicore OCaml implementation of an Evolutionary Algorithm.
Per Kristian Lehre <p.k.lehre@cs.bham.ac.uk>
May 6th, 2020 
"

open Cmdliner
module T = Domainslib.Task 

type bitstring = bool array
type individual = { chromosome : bitstring; fitness : float }
type fitness_function = bitstring -> float
type population = individual array

let chromosome_length = Array.length
let population_size = Array.length

let chromosome { chromosome=x; fitness=_ } = x
let evaluate f x = { chromosome=x; fitness=(f x) }

let fittest x y = if x.fitness > y.fitness then x else y
let pop_fittest pop = Array.fold_left fittest pop.(0) pop

let random_bitstring n =
  Array.init n (fun _ -> Random.bool ())

let random_individual n f =
  evaluate f (random_bitstring n)

(* Onemax is a simple fitness function. *)
let add_bit x b = if b then x +. 1.0 else x
let onemax : fitness_function = Array.fold_left add_bit 0.0

(* Choose fittest out of k uniformly sampled individuals *)
let rec k_tournament k pop =
  let x = pop.(Random.int (population_size pop)) in
  if k <= 1 then x
  else
    let y = k_tournament (k-1) pop in
    fittest x y 

let flip_coin p = (Random.float 1.0) < p
let xor a b = if a then not b else b
(* Naive Theta(n) implementation of mutation. *)
let mutate chi x =
  let n = chromosome_length x in
  let p = chi /. (float n) in
  Array.map (fun b -> xor b (flip_coin p)) x

(* Command line arguments *)

let num_domains =
  let doc = "Number of multicore domains." in
  Arg.(value & opt int 1 & info ["d"; "domains"] ~docv:"DOMAINS" ~doc)
  
let runtime = 
  let doc = "Number of function evaluations." in
  Arg.(value & opt int 100000 & info ["r"; "runtime"] ~docv:"RUNTIME" ~doc)

let chi = 
  let doc = "Mutation rate." in
  Arg.(value & opt float 0.4 & info ["c"; "chi"] ~docv:"CHI" ~doc)

let lambda = 
  let doc = "Population size." in
  Arg.(value & opt int 1000 & info ["l"; "lambda"] ~docv:"LAMBDA" ~doc)

let k = 
  let doc = "Tournament size." in
  Arg.(value & opt int 2 & info ["k"] ~doc)

let n = 
  let doc = "Problem instance size." in
  Arg.(value & opt int 1000 & info ["n"] ~doc)

let multicore_init pool num_domains x0 n f =
  let a = Array.make n x0 in
  T.parallel_for
    pool ~chunk_size:(n/num_domains) ~start:0 ~finish:(n-1)
    ~body:(fun i -> a.(i) <- f ());
  a

let evolutionary_algorithm

    num_domains   (* Number of multicore domains *)
    runtime       (* Runtime budget  *)
    lambda        (* Population size *)
    k             (* Tournament size *)
    chi           (* Mutation rate   *)
    fitness       (* Fitness function *)
    n             (* Problem instance size n *)

  =
  
  let pool = T.setup_pool ~num_domains:(num_domains - 1) in
  let adam = random_individual n fitness in
  let init_pop = multicore_init pool num_domains adam in
  let pop0 = init_pop lambda (fun _ -> random_individual n fitness) in

  let rec generation time pop =
    let next_pop = 
      init_pop lambda
	(fun _ ->
             (k_tournament k pop)
          |> chromosome
          |> (mutate chi)
          |> (evaluate fitness))
    in
    if time * lambda > runtime then
      (T.teardown_pool pool;
       Printf.printf "fittest: %f, num_domains: %d\n"
         (pop_fittest next_pop).fitness num_domains)
    else
      generation (time+1) next_pop
  in generation 0 pop0

let prg_info ?(doc="") name =
  Term.info name ~doc ~exits:Term.default_exits

let ea =
  Term.(const evolutionary_algorithm $ num_domains $ runtime $ lambda $ k $ chi $ const onemax $ n)

let () =
  Random.self_init ();
  Term.exit @@
  Term.eval (ea, prg_info ~doc "Multicore EA")

```
Example execution

```bash
$ for i in 1 2 3 8 16; do time dune exec -- ./multicore_ea.exe -d $i; done
Fittest 613.000000, num_domains: 1

real    0m4.535s
user    0m4.418s
sys     0m0.080s
Fittest 613.000000, num_domains: 2

real    0m5.437s
user    0m10.630s
sys     0m0.117s
Fittest 607.000000, num_domains: 3

real    0m4.851s
user    0m14.079s
sys     0m0.173s
Fittest 622.000000, num_domains: 8

real    0m21.822s
user    1m21.280s
sys     0m0.155s
Fittest 616.000000, num_domains: 16

real    0m29.128s
user    1m48.789s
sys     0m0.259s
```

**Comment by pklehre** [comment] 2020-05-06 16:01
``` bash
$ cat dune

(executable
 (name multicore_ea)
 (modules multicore_ea) 
 (libraries cmdliner domainslib))
```

**Comment by bluddy** [comment] 2020-05-06 20:49
Can you try this with one random state per domain as well? Evolutionary algorithms hit the random function constantly (as you suggest).

**Comment by pklehre** [comment] 2020-05-07 00:10
I've tried to follow the same approach as @Sudha247 in #333 however I still get a similar slowdown when increasing `num_domains`.

**Comment by pklehre** [comment] 2020-05-07 00:26
Looking at the comment by @stedolan it is difficult to create the random states within the domains using the setup_pool API. I can make a version which does not use the setup_pool API.

**Comment by bluddy** [comment] 2020-05-07 15:13
I modified your code similar to the way I did in #333. You can test out the improvements with different mult values.

```ocaml
let doc =
"
A minimal multicore OCaml implementation of an Evolutionary Algorithm.
Per Kristian Lehre <p.k.lehre@cs.bham.ac.uk>
May 6th, 2020 
"

open Cmdliner
module T = Domainslib.Task 

type bitstring = bool array
type individual = { chromosome : bitstring; fitness : float }
type fitness_function = bitstring -> float
type population = individual array

let chromosome_length = Array.length
let population_size = Array.length

let chromosome { chromosome=x; fitness=_ } = x
let evaluate f x = { chromosome=x; fitness=(f x) }

let fittest x y = if x.fitness > y.fitness then x else y
let pop_fittest pop = Array.fold_left fittest pop.(0) pop

let random_bitstring rstate n =
  Array.init n (fun _ -> Random.State.bool rstate)

let random_individual rstate n f =
  evaluate f (random_bitstring rstate n)

(* Onemax is a simple fitness function. *)
let add_bit x b = if b then x +. 1.0 else x
let onemax : fitness_function = Array.fold_left add_bit 0.0

(* Choose fittest out of k uniformly sampled individuals *)
let rec k_tournament rstate k pop =
  let x = pop.(Random.State.int rstate (population_size pop)) in
  if k <= 1 then x
  else
    let y = k_tournament rstate (k-1) pop in
    fittest x y 

let flip_coin rstate p = (Random.State.float rstate 1.0) < p
let xor a b = if a then not b else b
(* Naive Theta(n) implementation of mutation. *)
let mutate rstate chi x =
  let n = chromosome_length x in
  let p = chi /. (float n) in
  Array.map (fun b -> xor b (flip_coin rstate p)) x

(* Command line arguments *)

let mult =
  let doc = "Array multipler" in
  Arg.(value & opt int 1 & info ["m"; "mult"] ~docv:"MULT" ~doc)

let num_domains =
  let doc = "Number of multicore domains." in
  Arg.(value & opt int 1 & info ["d"; "domains"] ~docv:"DOMAINS" ~doc)
  
let runtime = 
  let doc = "Number of function evaluations." in
  Arg.(value & opt int 100000 & info ["r"; "runtime"] ~docv:"RUNTIME" ~doc)

let chi = 
  let doc = "Mutation rate." in
  Arg.(value & opt float 0.4 & info ["c"; "chi"] ~docv:"CHI" ~doc)

let lambda = 
  let doc = "Population size." in
  Arg.(value & opt int 1000 & info ["l"; "lambda"] ~docv:"LAMBDA" ~doc)

let k = 
  let doc = "Tournament size." in
  Arg.(value & opt int 2 & info ["k"] ~doc)

let n = 
  let doc = "Problem instance size." in
  Arg.(value & opt int 1000 & info ["n"] ~doc)

let random_states domains mult =
  Array.init (domains * mult) (fun _ -> Random.State.make_self_init ())

let multicore_init random_states mult pool num_domains x0 n f =
  let a = Array.make n x0 in
  T.parallel_for
    pool ~chunk_size:(n/num_domains) ~start:0 ~finish:(n-1)
    ~body:(fun i ->
      let d = (Domain.self () :> int) mod num_domains in
      a.(i) <- f random_states.(d * mult));
  a

let evolutionary_algorithm

    num_domains   (* Number of multicore domains *)
    mult          (* multiplier *)
    runtime       (* Runtime budget  *)
    lambda        (* Population size *)
    k             (* Tournament size *)
    chi           (* Mutation rate   *)
    fitness       (* Fitness function *)
    n             (* Problem instance size n *)

  =
  
  let pool = T.setup_pool ~num_domains:(num_domains - 1) in
  let rstates = random_states num_domains mult in
  let adam = random_individual rstates.(0) n fitness in
  let init_pop = multicore_init rstates mult pool num_domains adam in
  let pop0 = init_pop lambda (fun rstate -> random_individual rstate n fitness) in

  let rec generation time pop =
    let next_pop = 
      init_pop lambda
	(fun rstate ->
             (k_tournament rstate k pop)
          |> chromosome
          |> (mutate rstate chi)
          |> (evaluate fitness))
    in
    if time * lambda > runtime then
      (T.teardown_pool pool;
       Printf.printf "fittest: %f, num_domains: %d\n"
         (pop_fittest next_pop).fitness num_domains)
    else
      generation (time+1) next_pop
  in generation 0 pop0

let prg_info ?(doc="") name =
  Term.info name ~doc ~exits:Term.default_exits

let ea =
  Term.(const evolutionary_algorithm $ num_domains $ mult $ runtime $ lambda $ k $ chi $ const onemax $ n)

let () =
  Term.exit @@
  Term.eval (ea, prg_info ~doc "Multicore EA")
```

**Comment by pklehre** [comment] 2020-05-07 15:24
Thank you. On my machine, there is still a slow-down.

```bash
[pkl@phi multicore_ea]$ for i in 1 2 3 4; do time dune exec -- ./multicore_ea.exe --lambda 10000 -n 10000 -d $i -m 10; done
fittest: 5220.000000, num_domains: 1

real    0m58.173s
user    0m57.055s
sys     0m1.091s
fittest: 5201.000000, num_domains: 2

real    0m33.583s
user    1m3.970s
sys     0m2.243s
fittest: 5205.000000, num_domains: 3

real    0m33.087s
user    1m29.442s
sys     0m2.782s
fittest: 5177.000000, num_domains: 4

real    0m30.608s
user    1m46.934s
sys     0m2.033s

```

**Comment by bluddy** [comment] 2020-05-07 15:34
With `mult=10`, I get 10s for 1 domain, 7.5s for 2 domains, 4.2s for 4 domains, and 4.4s for 8 domains (I only have 4 cores, hyperthreaded).

**Comment by bluddy** [comment] 2020-05-07 15:56
Just to make it more comparable, with `--lambda 10000 -n 10000 -m 10`, 

domains | time(s)
--- | ---
1 |  128
4 | 51.2
8 | 31.6

**Comment by pklehre** [comment] 2020-05-07 15:59
OK, that is good to hear. I have an Intel Core i7-6600U CPU with 2 cores and 4 threads. 

The multiplication approach seems more like a hack. Perhaps the setup_pool API could be changed, so that one passes on a thunk unit -> 'a which is evaluated when the domain is constructed, and where the value of type 'a is passed on to the task. In this way, each domain could keep some separate state. In this particular case, one could pass on (fun () ->  Random.State.make_self_init ()).

**Comment by bluddy** [comment] 2020-05-07 16:20
While it's a hack, it's one that's commonly done in multi-threaded code. The problem isn't that there's cache overlap per se -- there's also cache overlap in the result array, but the array is large enough so as not to matter. The problem is that these threads are all hammering the same small bit of data in the same cache lines (specifically, the random state) and modifying it. Had the per-domain data been much larger, and the access pattern been random, it wouldn't have mattered.

Since it's a niche use-case, we could have a utility function in addition to `setup_pool` called `setup_pool_array` which could be used for this specific purpose, either making the actual allocation much bigger behind the scenes, or somehow distributing the allocation in memory. The problem with having a thunk as you suggest is that the type of 'a is lost, since setup_pool doesn't call the parallelized function. You'd have to store 'a in mutable state, and then retrieve it from the called parallel function.

**Comment by Sudha247** [comment] 2020-07-28 07:54
@pklehre now that we have Domain-local storage which was added in #372, we can store a Random State for every domain in its domain-local storage and use it to generate random values. I have used this idea and refactored your evolutionary algorithm to use DLS, which now seems to scale reasonably well. Performance numbers for `lambda = 10000 and n = 10000` are below and a speedup graph is [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vSq-3HFzdZzDketFIAuK5hGBaox2VAqy-vrLBNRqnCtB4PRkUjD1ZJFidW4ZjQh2Wer-COAs1f3G2fO/pubchart?oid=67097023&format=interactive):

Cores | Time(s) | Speedup
-- | -- | --
1 | 93.25 | 1
2 | 50.76 | 1.837076438
4 | 26.42 | 3.529523089
8 | 13.6 | 6.856617647
12 | 8.82 | 10.57256236
16 | 7.31 | 12.75649795
20 | 6.35 | 14.68503937
24 | 5.48 | 17.01642336

A PR to add the refactored code as a parallel benchmark to our benchmarking suite is here: https://github.com/ocaml-bench/sandmark/pull/151. We'd appreciate any feedback on this.

**Comment by kayceesrk** [comment] 2020-07-30 11:39
Fixed by https://github.com/ocaml-multicore/ocaml-multicore/pull/372 and https://github.com/ocaml-bench/sandmark/pull/151.

**Closed by kayceesrk** 2020-07-30 11:39 UTC

**Comment by pklehre** [comment] 2020-08-06 07:28
I confirm that I now get similar speedups. Thank you for your great work on the OCaml multicore implementation!

**Comment by kayceesrk** [comment] 2020-08-06 08:13
Thanks, @pklehre for your benchmark that helped motivate the work on domain-local state and identify and fix the issues with Radom state.
